import pt from 'prop-types';
import r from 'react';

export const PropTypes = pt;
export const React = r;
export { connect } from 'react-redux';
export { NotificationPage } from '../System/Notification/';
export { DialogPage } from '../System/Dialog/';
export { FluidApi } from 'fluid-commons';
export { Header } from '../System/Headers/';
export { PageAPI } from '../System/Page/';
export { DealerPage } from '../Forms/Dealer/';
export { PureComponent } from 'react';
export { Route, Switch } from 'react-router-dom';
export { Pages } from '../../types/';
export { RegistrationPage } from '../Forms/Registration/';
export { PolicyPage } from '../Forms/Policy/';
export { MaintenancePage } from '../Forms/Maintenance/';
export { RepairshopPage } from '../Forms/Repairshop/';
export { ClaimPage } from '../Forms/Claim/';
export { PolicyNewPage } from '../Forms/PolicyNew/';